apiVersion: v1
kind: ReplicationController
metadata:
  name: moviesearchnodejs-controller
spec:
  replicas: 2
  selector:
    app: moviesearchnodejs
  template:
    metadata:
      labels:
        app: moviesearchnodejs
    spec:
      containers:
      - name: moviesearchnodejs
        image: deepanshululla/movie_search_nodejs
        ports:
        - name: nodejs-port
          containerPort: 3000
