apiVersion: v1
kind: Service
metadata:
  name: moviesearch-nodejs-service
spec:
  ports:
  - port: 80
    targetPort: nodejs-port
    protocol: TCP
  selector:
    app: moviesearchnodejs
  type: LoadBalancer
